# Project Urban Rooftop Classification: Forth Notebook:Addresses and Lat/Long

From the screenshot to the classification 

### Geospatial dataset: Pre-Processing masks after Label Studio
 

In [27]:
#!pip install opencv-python 
import cv2
#!pip install glob2 
import glob
import os
import numpy as np
from PIL import Image
from matplotlib import pyplot as plt


In [64]:
def CategorizeMask(HouseNotationLS, label_folder):
    mask = np.zeros((400,400))
    for filename in HouseNotationLS:
        #print(filename)
        if "plane rooftop" in filename:
            #print(filename)
            PlaneMask = cv2.imread(filename, cv2.IMREAD_GRAYSCALE)
            #print(PlaneMask)
            PlaneMask = np.where(PlaneMask>0, 1, PlaneMask)
            mask = mask + PlaneMask
            #plane_masks.append(PlaneMask)
        elif "sattel rooftop" in filename:
            #print(filename)
            SattelMask = cv2.imread(filename, cv2.IMREAD_GRAYSCALE)
            SattelMask = np.where(SattelMask>0, 2, SattelMask)
            mask = mask + SattelMask
            #sattel_masks.append(SattelMask)
        elif "Trees" in filename:
            #print(filename)
            OtherMask = cv2.imread(filename, cv2.IMREAD_GRAYSCALE)
            OtherMask = np.where(OtherMask>0, 0, OtherMask)
            mask = mask + OtherMask
            #Other_masks.append(OtherMask)
    mask = np.where(mask>2, 2, mask) 
    return mask

# For Train Data

In [65]:
 #setting counter
label_folder = '/Users/robertroskoden/Documents/DataScieneBootcampSPICED/ds-capestone-project-DW89/data/data_for_training_and_testing/Masks/project-1-at-2023-10-09-17-47-ded5770a/Train_set'
TFileName = sorted(os.listdir('/Users/robertroskoden/Documents/DataScieneBootcampSPICED/ds-capestone-project-DW89/data/Data/Im/Orginal'))
if '.DS_Store'  in TFileName:                   # making sure there are not .DS_Store files
    print(TFileName)
    TFileName.pop(0)
    print(TFileName)
print(TFileName)
print(len(TFileName))
InNamePath = '/Users/robertroskoden/Documents/DataScieneBootcampSPICED/ds-capestone-project-DW89/data/data_for_training_and_testing/Masks/MultiMasks/NoTrees/Train/'


['001_Steglitzer_Sate.png', '002_Attilastraße_Sate.png', '005_Attilastraße_Sate.png', '006_Attilastraße_Sate.png', '009_Alt-Lankwitz_Sate.png', '009_Ritterstraße_Sate.png', '010_Attilastraße_Sate.png', '012_Steglitzer_Sate.png', '014_Attilastraße_Sate.png', '017_Steglitzer_Sate.png', '020_Steglitzer_Sate.png', '022_Ritterstraße_Sate.png', '025_Steglitzer_Sate.png', '026_Ritterstraße_Sate.png', '028_Steglitzer_Sate.png', '029_Attilastraße_Sate.png', '031_Ritterstraße_Sate.png', '034_Steglitzer_Sate.png', '035_Ritterstraße_Sate.png', '039_Alt-Lankwitz_Sate.png', '039_Steglitzer_Sate.png', '041_Ritterstraße_Sate.png', '042_Ritterstraße_Sate.png', '042_Steglitzer_Sate.png', '045_Ritterstraße_Sate.png', '047_Steglitzer_Sate.png', '048_Alt-Lankwitz_Sate.png', '049_Alt-Lankwitz_Sate.png', '052_Ritterstraße_Sate.png', '056_Ritterstraße_Sate.png', '056_Steglitzer_Sate.png', '059_Attilastraße_Sate.png', '060_Attilastraße_Sate.png', '061_Steglitzer_Sate.png', '064_Attilastraße_Sate.png', '070_Ste

In [66]:
F1 = []                                                         #creating empty list for
OneHouse = []                                                   #creating empty list for
counter = 1 
##########################################################################################################################################################
################### Loop to list masked and save them with a new name ####################################################################################
##########################################################################################################################################################
for i in range(0,62): #because there 62 images 
    F0 = 'task-' + str(counter) +'-*'
    F1.append(F0)
    NewTask = os.path.join(label_folder, F1[i] )
    HouseNotationLS = glob.glob(NewTask)
    mask = CategorizeMask(HouseNotationLS, label_folder)
    #print(i)
    #print(TFileName[i])
    ImName = InNamePath + TFileName[i]#+ TFileName[i] 
    np.save('ImName', mask)
    ImName2 = ImName #+'.png'
    cv2.imwrite(ImName2, mask)
    print(counter)
    print(np.unique(mask))
    counter += 1

1
[0. 1. 2.]
2
[0. 2.]
3
[0. 2.]
4
[0. 2.]
5
[0. 2.]
6
[0. 2.]
7
[0. 1. 2.]
8
[0.]
9
[0. 2.]
10
[0. 2.]
11
[0. 1.]
12
[0. 1.]
13
[0. 2.]
14
[0. 1.]
15
[0. 1. 2.]
16
[0. 2.]
17
[0. 1.]
18
[0. 1. 2.]
19
[0. 1.]
20
[0. 2.]
21
[0. 2.]
22
[0. 2.]
23
[0. 2.]
24
[0. 1. 2.]
25
[0. 2.]
26
[0. 1.]
27
[0. 1. 2.]
28
[0. 1.]
29
[0.]
30
[0. 1. 2.]
31
[0. 1. 2.]
32
[0. 1. 2.]
33
[0. 2.]
34
[0.]
35
[0.]
36
[0. 1. 2.]
37
[0. 1.]
38
[0. 1.]
39
[0. 2.]
40
[0. 2.]
41
[0. 1.]
42
[0. 1.]
43
[0. 2.]
44
[0. 1.]
45
[0.]
46
[0. 1. 2.]
47
[0. 1.]
48
[0. 1.]
49
[0. 2.]
50
[0. 2.]
51
[0. 2.]
52
[0. 1. 2.]
53
[0. 1. 2.]
54
[0. 1. 2.]
55
[0. 2.]
56
[0. 1.]
57
[0. 1. 2.]
58
[0. 1. 2.]
59
[0. 1. 2.]
60
[0. 2.]
61
[0. 2.]
62
[0. 1. 2.]


In [67]:
print(np.unique(mask))

[0. 1. 2.]


## Same for Val Data

In [68]:
 #setting counter
label_folder = '/Users/robertroskoden/Documents/DataScieneBootcampSPICED/ds-capestone-project-DW89/data/data_for_training_and_testing/Masks/project-1-at-2023-10-09-17-47-ded5770a/Val-Set'
TFileName = sorted(os.listdir('/Users/robertroskoden/Documents/DataScieneBootcampSPICED/ds-capestone-project-DW89/data/Data/Im/Extra'))
if '.DS_Store'  in TFileName:                   # making sure there are not .DS_Store files
    print(TFileName)
    TFileName.pop(0)
    print(TFileName)
print(len(TFileName))
InNamePath = '/Users/robertroskoden/Documents/DataScieneBootcampSPICED/ds-capestone-project-DW89/data/data_for_training_and_testing/Masks/MultiMasks/NoTrees/Val/'

18


In [69]:
F1 = []                                                         #creating empty list for
OneHouse = []                                                   #creating empty list for
counter = 63 
counter2 = 0
##########################################################################################################################################################
################### Loop to list masked and save them with a new name ####################################################################################
##########################################################################################################################################################
for i in range(63,81): #because there 62 images 
    F0 = 'task-' + str(counter) +'-*'
    F1.append(F0)
    NewTask = os.path.join(label_folder, F1[counter2] )
    HouseNotationLS = glob.glob(NewTask)
    mask = CategorizeMask(HouseNotationLS, label_folder)
    #print(i)
    #print(TFileName[i])
    ImName =InNamePath + TFileName[counter2]#'task-' +  str(counter) 
    np.save('ImName', mask)
    ImName2 = ImName #+'.png'
    cv2.imwrite(ImName2, mask)
    print(counter)
    print(np.unique(mask))
    counter += 1
    counter2 += 1

63
[0.]
64
[0. 2.]
65
[0. 1. 2.]
66
[0. 2.]
67
[0. 2.]
68
[0. 2.]
69
[0. 1.]
70
[0. 1.]
71
[0. 2.]
72
[0. 1.]
73
[0. 1.]
74
[0. 2.]
75
[0. 1. 2.]
76
[0. 2.]
77
[0. 1.]
78
[0. 2.]
79
[0.]
80
[0. 1. 2.]


In [54]:
#import pandas as pd
print(mask.shape)
print(type(mask))
print(np.unique(mask))

(400, 400)
<class 'numpy.ndarray'>
[0. 1. 2.]
